title: <p align="center"> Alok Abhayajith </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/alok-abhayajith/">LinkedIn</a> |
  <a href="https://github.com/alokabhayajith">GitHub</a>
  
  <br>   
  Currently I'm an absolute beginner to the field of machine learning and artificial intellignece.
  <br>
  </p>



theme: jekyll-theme-minimal
